### ISSUE TITLE
Normalize the joint space for the Kuka?

### ISSUE THREAD

**Issue by carlosjoserg** [CentroEPiaggio/pacman-DR53#16]
@hamalMarino The SoftHand already operates in [0,1]. Do you think it is beneficial to do the same for the arm? How that would affect the low-level planner implementation?

I think it might have influence in #12.

/cc @manuelbonilla @MirkoFerrati

**Comment by hamalMarino** [comment]
I don't see any reason for that: this will need linear scaling inversion for each joint, and there is no benefit in having [0,1] joints instead of real limit values: that info comes with geometry anyway, and we need geometry...
If you see any reason for that let's discuss it, I'm open but I don't see any benefit right now

**Comment by manuelbonilla** [comment]
I don't see any reason either. I'm almost sure that all planners do it internally.

**Comment by carlosjoserg** [comment]
> I'm almost sure that all planners do it internally.

Now that you mention it, yes, it is highly probable that OMPL does it that way.

Ok, I consider my doubt clarified. Thanks!
