### ISSUE TITLE
Object Pose Estimation

### ISSUE THREAD

**Issue by carlosjoserg** [CentroEPiaggio/pacman-DR53#19]
The current state of the object pose estimation recognizes point cloud patches and not an object mesh. Hence, the reference coordinate frame for the object is not unique. Things to do:
- [x] Object scan of IKEA objects (all possible objects from the list)
- [x] [Point cloud registration](http://pointclouds.org/documentation/tutorials/registration_api.php) of all scans of an object
- [x] Mesh generation (e.g. using [meshlab stuff](http://meshlabstuff.blogspot.com.es/2009/09/meshing-point-clouds.html), leave it dense, and provide instructions to downsample, unless the mesh is too heavy)
- [x] Submit to [pacman-object-database](https://github.com/pacman-project/pacman-object-database)

This is a pre-requisite of #5 since it is needed to calibrate the star tracker with objects.

**Comment by carlosjoserg** [comment]
@Tabjones I think we can tick all items in the list above since the procedure is established, and object pose estimation is working, right? At least for few objects it is there.

**Comment by Tabjones** [comment]
@carlosjoserg Yes currently all steps above are accomplished for a few objects (5). I was waiting to have all the objects, but i can tick them and leave the issue open until all objects are completed.

**Comment by carlosjoserg** [comment]
:+1:

**Comment by carlosjoserg** [comment]
Hey @Tabjones , I see that the pose estimation depends on [1.7.2 of PCL](https://github.com/CentroEPiaggio/pose_estimation_online/blob/0de4c2851d8d803598f51b354af8dc6ad8bfa5ca/CMakeLists.txt#L9) 

And I can't find it as a standard package in synaptics/apt-get, only 1.7.1 is there, or perhaps I'm missing another repository. Can you confirm that requirement?

Another thing, the install of [this](https://bitbucket.org/Tabjones/pel) should be automated. It'd be good if the whole `pacman-DR53` compiles with a single `catkin_make` command. My suggestion (to keep your repos clean): try convertin the perception folder as a meta-package, and add post-build and dependencies CMake commands.

**Comment by Tabjones** [comment]
yo @carlosjoserg, yes it needs pcl 1.7.2. i'm using some functionalities that are not there in 1.7.1, and yes ubuntu 14.04 doesn't have it.
Recommended way to solve this is to clone [pcl github repo](https://github.com/PointCloudLibrary/pcl),
check out to 1.7.2  (`git checkout pcl-1.7.2`), configure and make install it (it will go in /usr/local/lib).
cmakelists in perception packages are configured to give priority to the local installed pcl instead of the system one. Cmake will complain a bit, it will tell you that you are "hiding" some libraries in /usr/lib in favor of some in /usr/local/lib, (thanks a lot, that was what i was trying to do!) but everything will work fine.
Yes i should probably mention this in the various readmes, and will do it.

As for the second thing, i'm not sure how i can tell catkin to make install a 3rd party library, before it actually tries to build perception packages, but i will look into it. Probably what you are suggesting is the correct/recommended way to do this.

**Comment by carlosjoserg** [comment]
> Recommended way to solve this...

Ok, no standard synaptic/apt-get then, so I would suggest to automate the process of getting it. Two options I can think of: 
- Add it as a sub-module pointing at the tag `pcl-1.7.2` to fix the version. But one still need to build and install as a dependency.
- Try the CMake feature for an [ExternalProject](http://www.cmake.org/cmake/help/v3.0/module/ExternalProject.html), and add it to PEL, so you can download at the specified tag, compile and install using CMake.

> As for the second thing, i'm not sure how i can tell catkin to make install a 3rd party library, before it actually tries to build perception packages...

You can use standard CMake for that as well, even within catkin, for instance a POST-BUILD custom command like [this one](https://bitbucket.org/dualmanipulation/shared/src/a3f2e8b4e56e2d31d7353c1320e548ae667ef0d8/CMakeLists.txt?at=master#cl-98) might be a good option,  but in your case as a PRE-BUILD. [Here](http://www.cmake.org/cmake/help/v3.0/command/add_custom_command.html) you have the full specs.

**Comment by carlosjoserg** [comment]
@Tabjones  Should we close this?

**Comment by Tabjones** [comment]
Yes !
