### ISSUE TITLE
Milstone: Solution to planning problems

### ISSUE THREAD

**Issue by carlosjoserg** [CentroEPiaggio/pacman-DR53#21]
Hi @CentroEPiaggio/pacmandemoteam

We are in a **very serious situation**. This is the THIRD milestone since the IROS submission and we haven't been able to run a single complete demo, with Marco present.

Today, we found the issues below, so please, check the list, and take actions for what it concerns you that you consider critical, apart from the last one that is already labeled as critical, so that the next milestone (next Wednesday) we can see RUNTIME errors.
- [ ] PLEASE: use the `git submodule` structure to fix the commit/tag of the [dualmanipulation](https://bitbucket.org/dualmanipulation/dualmanipulation) repo within the [pacman-DR53](https://github.com/CentroEPiaggio/pacman-DR53) as if it were a dependency with a version. Right now is `dualmanipulation @ e148500` **<- I'm not going to update this anymore, unless you tell me a specific commit/tag to do so**
- [x] Packages ik_control and state_manager publish all the time the debug message: `ikCheckCapability::scene_callback : updating planning scene`  **<- it consumes resources, and we are not good at it for now**.
- [ ] Gui: the graph picture is not updated until the window is resized **<- not really an error, but it is confusing**
- [x] Package `pose_estimation_online` is not integrated in the gui: the service name is wrong, the correct one is `/pose_estimation_online/estimate`.
- [x] Package `pose_estimation_online` is not compiling with a single catkin_make command (please, automate the database download as well).
- [x] When clicking the home button, state_manager prints: `[ WARN]: There was an error, ik_control returned msg.data : done` everytime, but the robot goes home anyway **<- not really an error, but it is confusing**
- [x] [CRITICAL] After a high-level plan is found, and all ik-check has been done, you see in the figure below the plan to grasp, but it does not execute the trajectory (it is not the connection, because the homing is perfomed correctly). We couldn't move forward from here.
  ![screenshot](https://dl.dropboxusercontent.com/u/16526900/Screenshot%20from%202015-04-17%2019%3A40%3A07.png)

Thanks
Carlos

**Comment by hamalMarino** [comment]
Most of the problems were due to a couple of wrong commits which weren't tested in the version included in pacman-DR53, now they are fixed.
Moreover, a bunch of new fixes have been performed, and the current version of the demo is [pretty much, not perfectly] working, apart from the grasps which are seemingly not good enough.
I didn't update pacman-DR53 yet cause there are another bunch of small fixes which should be beneficial, especially for clarity, for the "pilot".

A _SERIOUS_ problem, instead, is the workspace of Vito, which is incredibly small... I think we should prepare some sort of capability map for our robot, and actually have it printed close to Vito itself (maybe a nice, colored one, for the reviewers when they'll come and move objects around...)

**Comment by carlosjoserg** [comment]
The non-checked points are not critical, closing.
