### ISSUE TITLE
IMU-based glove integration

### ISSUE THREAD

**Issue by carlosjoserg** [CentroEPiaggio/pacman-DR53#8]
@GaspareSantaera @emalbt  are you willing to set a github repository for your implementation? You can set it privately for now, until you decide if you want to open-source it or not. It would definitely help to integrate it in the demo. I can help you shape it as with the flexiforce-based glove: https://github.com/CentroEPiaggio/flexiforce-glove

**Comment by carlosjoserg** [comment]
Hi @GaspareSantaera @emalbt , any feedback on this?

/cc @hamalMarino

**Comment by GaspareSantaera** [comment]
I'm working on realization of two new gloves (left-right), because I want to create a stand-alone device attached to the hand and connected to computer by an usb.I'm trying to replace the current hardware, (who is based on a PSoC 5) using a PSoC 3 to reduce the hardware space, if PSoC 3 don't work properly I will try to use another hardware like STM32 Discovery board, who is more powerful with respect the PSoC 5.Moreover I have some problem to buy IMUs but I think to overcome them in this week.See you soonGaspare 

----Messaggio originale----

Da: notifications@github.com

Data: 16/03/2015 13.18

A: "CentroEPiaggio/pacman-DR53"pacman-DR53@noreply.github.com

Cc: "GaspareSantaera"santaeragaspare@inwind.it

Ogg: Re: [pacman-DR53] IMU-based glove integration (#8)

Hi @GaspareSantaera @emalbt , any feedback on this?

/cc @hamalMarino

**Comment by carlosjoserg** [comment]
Thanks of the update, looks promising as a stand-alone device indeed. Looking forward to see both hands sensorized !

**Comment by carlosjoserg** [comment]
The demo of the glove is separated.

We will work with the @GaspareSantaera 's idea of using the motor joint to estimate whether there was a successful grasp or not.
